# service port, *reboot required
service_port = ":8080"
# log output level
log_level = "info"
# log file path, *reboot required
log_file = "./base-server.log"
# max cpu num rate
max_cpu_rate = 50
# i18n config files root path
i18n_root_path = "./configs/messages"
# language
language = "zh_CN"
